### ISSUE TITLE
How to start things up ?

### ISSUE THREAD

**Issue by Bibi40k** [bjw-s/home-ops#2096]
Hi,
i'd like to use your work to create my first home cluster (zero experience on that).
I first tried **k8s-at-home/template-cluster-k3s**, i followed all the steps and it worked but i'd like to use yours so i'm "yelling" for a little help. Actually is a big please.

Hardware that i have:
- Mikrotik router which seems able to work with CoreDNS
- TrueNas for storage
- XCP-ng Hypervisor for VMs

Things that confuses me:
- i don't see any ansible so how can i deploy cluster (seems to be in .gitignore) ?
- what is "siderio", it seems is another cluster that deploys "cluster-o" ?
- is a must to have multiple nodes for this cluster to work ?

Could you lease help me with some hints to deploy the cluster, set networks, storages, lb, dns ? :)

Thank you

**Comment by Bibi40k** [comment]
I've checked old commits where you removed /ansible from project so how you create/update/remove  cluster and how you generate all sop secrets from each manifest/app ?

**Comment by Bibi40k** [comment]
Are you that busy so you can't help me with some hints ?

**Comment by bjw-s** [comment]
> Are you that busy so you can't help me with some hints ?

Yes, I have been.

> i don't see any ansible so how can i deploy cluster (seems to be in .gitignore) ?

There is no Ansible involved. See below.

> what is "siderio", it seems is another cluster that deploys "cluster-o" ?

Yes, it is exactly that ([link](http://sidero.dev)). 

> is a must to have multiple nodes for this cluster to work ?

Yes, because (amongst other reasons) my storage cluster requires 3 replica's.

In general, my repo can serve as an inspiration for anyone to get their own cluster set up, but trying to do so will require some basic understanding of how to set up a cluster. Unfortunately I do not have the time to provide any support services on those steps.

**Comment by Bibi40k** [comment]
Thanks
